### PR TITLE
Resharper color identifiers and default dark colors

### PR DESCRIPTION
**Pull request by doticca**
Added default color identifiers using latest version of Resharper.
Edited color identifiers to use OneDakrPro background color and Resharper's default dark front colors.

It may need a few color tweaks to be 100% compatible with the rest of the theme but it should solve #6

### CODE REVIEW

**Comment by AdrianWilczynski** [comment]
Hi, thanks for your contribution.  I'm gonna check it out and merge it soon.

I'm curious how did you find these/know what to add? I tried searching for `Resharper` in `Visual Studio Color Theme Designer` before and it didn't turn up much.

**Comment by doticca** [comment]
Hello Adrian,

I have my resharper installed.
Switched to default dark theme.
Made a copy of OneDarkPro in the VS theme editor and I noticed that the default light theme color identifiers where created.
Opened both; The copy and the default dark theme (that already had the default dark theme resharper identifiers).
Started copying values from default to OneDarkPro.
Exported the OneDarkCopy and added only the resharper values to your solution.

Please have in mind that these are the default color values for the Dark theme of Resharper, I only used the background color from OneDarkPro so you might need to tweak them a bit to match your theme 100%.

I am already using it, and the only value that needs to be changed so far is the selected text background (it is the same as the background and you cannot see any difference)

Best Regards,
Fotis

**Comment by AdrianWilczynski** [comment]
Thanks for the explanation.

I've installed Resharper and it doesn't really seem to fix #6. It looks like (correct me if I'm wrong) you copied properties responsible only for text and syntax highlighting? `Templates Explorer` still has the light grey bars.

Are there some issues with syntax highlighting as well (with Reshaper but without your changes)?

Your explanation is super helpful though. If I create a new theme with Resharper installed there are some Resharper specific properties that control `Templates Explorer` (like `LTSelectedGradientEnd`). So I'm gonna copy them.

I just don't know if I need to copy the ones responsible for text as well? They don't really seem to change anything on my end. Text selection also looks fine.

**Comment by doticca** [comment]
I noticed that you didn't apply the whole bunch of Resharper properties that exists in the Pull Request. Only a few of them and only with the default values.

**Comment by AdrianWilczynski** [comment]
Yeah, I know. That's what I'm asking about. Are they necessary? They didn't seem to change anything on my end.

**Comment by AdrianWilczynski** [comment]
But I'm not a ReSharper user so I might be missing something.

**Comment by AdrianWilczynski** [comment]
I only copied UI (`Templates Explorer`) related properties for now. The ones with default/invalid values got auto generated when saving.

**Comment by doticca** [comment]
yes it looks like all of them are necessary as they are in the pull request for me to work

**Comment by AdrianWilczynski** [comment]
Could you add some screenshots so I know what to look for?

**Comment by doticca** [comment]
why don't you just merge the Pull Request? it contains only the new rows for resharper's color identifiers

**Comment by AdrianWilczynski** [comment]
I just want to know what they do.

**Comment by doticca** [comment]
To understand what they do you have to install latest version of Resharper (free/demo will do). 
Each region (for example Resharper C# bunch of settings) defines coloring of various text editor properties when you open a .cs file. Some of these properties are only noticeable from experienced Resharper users.
When resharper coloring is on (resharper settings), all blocks of documents in text editor get special colors depending on various resharper rules. I wish I could help more but for that you better speak with their technical support. 
They also provide free licenses for open source projects.

**Comment by AdrianWilczynski** [comment]
Do you know how can I enable ReSharper coloring? I found:

example

But it seems broken either way.

**Comment by AdrianWilczynski** [comment]
Okay, never mind. I forgot to switch the branch 😅

It ends up looking like this:

example

So yeah, it seems like an improvement over previous unreadable colors.

Sorry about being so annoying about this 😅

**Comment by doticca** [comment]
Haha no worries.

And yes this is the default resharper color scheme.
As you can see there is an issue with the selected text (very similar to your background)
And you might want to match resharper colors with your colors but this will need lot of testing from your side.

But it works very nice at the moment. I am already using it with no issues.

**Comment by AdrianWilczynski** [comment]
I've integrated your changes. I'm gonna close this PR now but it's all included anyway.

**Comment by AdrianWilczynski** [comment]
Thanks again!

**Pull request closed without merging**
