### PR TITLE
feat: add support for visual studio 2022 preview 1

### PR DESCRIPTION
**Pull request by MrCSharp22**
A simple target version range update to allow Dark One Pro to run under Visual Studio 2022 Preview 1

### CODE REVIEW

**Comment by AdrianWilczynski** [comment]
Thanks for the PR. I'll try to test and push it out soon.

**Comment by AlexMax** [comment]
Looking forward to it.  I am an avid user of your theme.

**Comment by pwuersch** [comment]
Would be awesome to have this in the marketplace for the 2022 edition. Really like your theme.

**Comment by AdrianWilczynski** [comment]
Hey, thanks again for the pull request, and sorry that it took me so long to act on it. Visual Studio 2022 should be supported now.

I wasn't familiar with the process of porting extensions to Visual Studio 2022, and I didn't feel qualified to review this PR. I wanted to go through the steps myself to understand it better. Since I let this PR go a bit stale (we're at preview 4 now), I've decided to commit the changes instead of merging it. Your PR was really helpful as a reference.

**Comment by pwuersch** [comment]
Nice, thanks @AdrianWilczynski for adding the extension to the new Visual Studio. Finally I can get my old familiar IDE look again 😄

**Comment by MrCSharp22** [comment]
Thanks @AdrianWilczynski. Glad I could help with this :)

**Pull request closed without merging**
