### PR TITLE
Improves vertical tab theming

### PR DESCRIPTION
**Pull request by fossbrandon**
The current theme has issues with vertical tabs that can be seen in issues #20 and #14 . 

This PR includes the addition of a missing field in the theme and modifications to others to make vertical tabs more usable. 

**Note:** I used colors already included in the theme and created an additional color inspired by how the default dark theme handles vertical tabs. (They also created a unique color for this). Please let me know if you prefer different colors than the ones I selected and I would be happy to change them.

Inactive state:
image

Active state:
image

### CODE REVIEW

**Comment by ryanbuening** [comment]
@AdrianWilczynski any chance of merging this in?

**Comment by ryanbuening** [comment]
@fossbrandon do you have any interest in forking this repo and releasing your changes to the marketplace? It doesn't appear that @AdrianWilczynski is working on this anymore.

**Comment by AdrianWilczynski** [comment]
Hey, thanks for the PR. Sorry for the delay 😓

**Comment by fossbrandon** [comment]
No worries, thanks for taking a look!

**Pull request merged**
